language: python
dist: xenial
python:
  # To see supported options, run:
  #   s3cmd ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/
  # We put pypy first, b/c for tests they're the slowest
  - pypy2.7-6.0
  - pypy3.5-6.0
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

before_install:
  - pip install -U pip setuptools wheel
  - pip install -Ur test-requirements.txt
  - pip install codecov

script:
  - pytest --cov=h11 --cov-config=.coveragerc h11

after_success:
  - codecov
